version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./coreza-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./coreza-backend:/app
    env_file:
      - ./coreza-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery-worker:
    build: ./coreza-backend
    command: celery -A scheduler.services.queue.celery_app worker --loglevel=info --pool=solo
    volumes:
      - ./coreza-backend:/app
    env_file:
      - ./coreza-backend/.env
    depends_on:
      - redis
      - backend

  frontend:
    build: .
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
