databases:
  - name: coreza-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

services:
  - type: web
    name: coreza-backend
    env: docker
    plan: free
    dockerfilePath: ./coreza-backend/Dockerfile.prod
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: coreza-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: "https://tiitofotheupylvxivge.supabase.co"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpaXRvZm90aGV1cHlsdnhpdmdlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDkyNzI0MSwiZXhwIjoyMDY2NTAzMjQxfQ.azjdmYIYlqd9-CBTuHoPHux_PUs97Dk4jpP_2RX9_n8"
      - key: ENVIRONMENT
        value: "production"

  # Optional: Comment out if staying free-only (Celery worker needs Starter plan)
  - type: worker
    name: coreza-worker
    env: docker
    plan: starter
    dockerfilePath: ./coreza-backend/Dockerfile.worker
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: coreza-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: "https://tiitofotheupylvxivge.supabase.co"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpaXRvZm90aGV1cHlsdnhpdmdlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDkyNzI0MSwiZXhwIjoyMDY2NTAzMjQxfQ.azjdmYIYlqd9-CBTuHoPHux_PUs97Tk4jpP_2RX9_n8"
      - key: ENVIRONMENT
        value: "production"

  - type: web
    name: coreza-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: coreza-backend
          type: web
          property: host
