databases:
  - name: coreza-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

services:
  - type: web
    name: coreza-backend
    env: docker
    plan: free
    dockerfilePath: ./coreza-backend/Dockerfile.prod
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: coreza-redis
          property: connectionString
      - key: SECRET_KEY
        value: "change-me"

  # Remove or upgrade this if free plan blocks it
  - type: worker
    name: coreza-worker
    env: docker
    plan: starter   # or comment this whole block out if you can't upgrade
    dockerfilePath: ./coreza-backend/Dockerfile.worker

  - type: web
    name: coreza-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
