databases:
  - name: coreza-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

services:
  - type: web
    name: coreza-backend
    env: docker
    plan: free
    dockerfilePath: ./coreza-backend/Dockerfile.prod
    contextPath: ./coreza-backend
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: coreza-redis
          property: connectionString
      - key: SECRET_KEY
        value: "change-me"

  - type: worker
    name: coreza-worker
    env: docker
    plan: starter          # change/remove if you don't want worker now
    dockerfilePath: ./coreza-backend/Dockerfile.worker
    contextPath: ./coreza-backend
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: coreza-redis
          property: connectionString
      - key: SECRET_KEY
        value: "change-me"

  - type: web
    name: coreza-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
