services:
  - type: web
    name: coreza-backend
    env: docker
    plan: free
    dockerfilePath: ./coreza-backend/Dockerfile.prod
    envVars:
      - key: REDIS_URL
        fromService:
          name: coreza-redis
          type: redis
          property: connectionString

  - type: worker
    name: coreza-worker
    env: docker
    plan: free
    dockerfilePath: ./coreza-backend/Dockerfile.worker
    envVars:
      - key: REDIS_URL
        fromService:
          name: coreza-redis
          type: redis
          property: connectionString

  - type: redis
    name: coreza-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all

  - type: web
    name: coreza-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    rootDir: frontend
