FROM python:3.11-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1

COPY coreza-backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY coreza-backend/ /app

CMD ["celery", "-A", "scheduler.services.queue.celery_app", "worker", "--loglevel=info", "--pool=solo"]
